[package]
name = "dht22_reader"
version = "0.1.0"
edition = "2021"

[dependencies]
bindgen = "0.72.0"
thiserror = "2.0.11"

[dev-dependencies]
simple_test_case = "1.2.0"

[build-dependencies]
bindgen = "0.72.0"

[features]
generate-bindings = []
